version: '3'

services:

  # Mandatory services
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: on-failure
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: on-failure
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html

  # Bonus services
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis
    restart: on-failure
    networks:
      - inception

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    image: ftp
    restart: on-failure
    ports:
      - "21:21"
      - "40000-40100:40000-40100"
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - inception
    depends_on:
      - mariadb

  uptime-kuma:
    build: ./requirements/bonus/uptime-kuma
    container_name: uptime-kuma
    image: uptime-kuma
    restart: on-failure
    ports:
      - "3001:3001"
    networks:
      - inception
    volumes:
      - uptime-kuma:/app
  
  static:
    build: ./requirements/bonus/static
    container_name: static
    image: static
    restart: on-failure
    ports:
      - "4242:4242"
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:

  # Mandatory volumes
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind
  
  # Bonus volumes
  uptime-kuma:
    driver: local
    name: uptime-kuma
    driver_opts:
      type: none
      device: ~/data/uptime-kuma
      o: bind