version: '3'

services:

  # Mandatory services
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html

  # Bonus services
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: always
    ports:
      - "21:21"
      - "40000-40100:40000-40100"
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - inception
    depends_on:
      - mariadb

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind